=== Mitrano-sensei/APP5-Schema-de-donn-e/src/providers/forms/forms.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="form">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="question">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string"/>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="select">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="question">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string"/>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="option" type="xs:string" minOccurs="2" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Mitrano-sensei/APP5-Schema-de-donn-e/src/providers/forms/form1.xml
<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="forms.xsd">
    <question>
        Quelle est votre couleur préférée ?
    </question>
    <select>
        <question>Quel est votre animal préféré ?</question>
        <option>Chien</option>
        <option>Chat</option>
        <option>Oiseau</option>
    </select>
    <question>
        Quel est votre plat préféré ?
    </question>
</form>
